// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import NavigationController from "./navigation_controller.js";
application.register("navigation", NavigationController);

import StarBarController from "./star_bar_controller.js";
application.register("star-bar", StarBarController);

import SubmitFormController from "./submit_form_controller.js";
application.register("submit-form", SubmitFormController);
